import {
    androidstudio,
    atomone,
    dracula,
    darcula,
    githubDark,
    githubLight,
    gruvboxDark,
    gruvboxLight,
    materialDark,
    materialLight,
    monokai,
    nord,
    solarizedDark,
    solarizedLight,
    sublime,
    tokyoNight,
    tokyoNightStorm,
    vscodeDark,
    xcodeDark,
    xcodeLight,
  } from "@uiw/codemirror-themes-all";
  
export const editorThemes = {
  "Android Studio": androidstudio,
  "Atom One": atomone,
  Darcula: darcula,
  Dracula: dracula,
  "GitHub Dark": githubDark,
  "GitHub Light": githubLight,
  "Gruvbox Dark": gruvboxDark,
  "Gruvbox Light": gruvboxLight,
  "Material Dark": materialDark,
  "Material Light": materialLight,
  Monokai: monokai,
  Nord: nord,
  "Solarized Dark": solarizedDark,
  "Solarized Light": solarizedLight,
  Sublime: sublime,
  "Tokyo Night": tokyoNight,
  "Tokyo Night Storm": tokyoNightStorm,
  "VS Code Dark": vscodeDark,
  "Xcode Dark": xcodeDark,
  "Xcode Light": xcodeLight,
};